name: flawfinder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 17 * * 6'

jobs:
  flawfinder:
    name: Flawfinder Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        component:
          - src
          - include
          - tests # Add other directories as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Flawfinder on ${{ matrix.component }}
        uses: david-a-wheeler/flawfinder@v1.0.0 # Replace with the latest tag
        with:
          arguments: "--sarif ./${{ matrix.component }}"
          output: "flawfinder_results_${{ matrix.component }}.sarif"

      - name: Upload results for ${{ matrix.component }} to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/flawfinder_results_${{ matrix.component }}.sarif

      - name: Save results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flawfinder-results-${{ matrix.component }}
          path: flawfinder_results_${{ matrix.component }}.sarif

  notify:
    name: Notifications
    runs-on: ubuntu-latest
    needs: flawfinder
    if: always()
    steps:
      - name: Send notification to Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Flawfinder analysis failed on branch ${{ github.ref }}. Please check the results."
      - name: Notify success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Flawfinder analysis completed successfully on branch ${{ github.ref }}."
